import React,{Suspense,useEffect,useMemo,useRef,useState}from'react'
import{Canvas,useFrame,useThree}from'@react-three/fiber'
import{OrbitControls,Html,useGLTF}from'@react-three/drei'
import*as THREE from'three'
const BIKE='/models/motorbike.glb'

function Bike({refObj,position=[0,0,0],scale=1}){
 const{scene}=useGLTF(BIKE)
 const clone=useMemo(()=>scene.clone(true),[scene])
 const fit=useMemo(()=>{clone.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(clone);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());return{scale:3.8/Math.max(size.x,size.y,size.z,1),offset:new THREE.Vector3(-center.x,-box.min.y,-center.z)}},[clone])
 useEffect(()=>{clone.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material)o.material.side=THREE.DoubleSide}})},[clone])
 return <group ref={refObj} position={position} scale={fit.scale*scale}><primitive object={clone} position={fit.offset}/></group>
}
useGLTF.preload(BIKE)

function Garage(){return <group><mesh position={[0,-.15,0]} receiveShadow><boxGeometry args={[24,.25,18]}/><meshStandardMaterial color="#111a20" roughness={.7} metalness={.3}/></mesh><gridHelper args={[24,48,'#1a5360','#09171e']} position={[0,.01,0]}/><mesh position={[0,4,-8.8]}><boxGeometry args={[24,8,.2]}/><meshStandardMaterial color="#071117"/></mesh>{[-11.9,11.9].map(x=><mesh key={x} position={[x,3,0]}><boxGeometry args={[.2,6,18]}/><meshStandardMaterial color="#09131a"/></mesh>)}</group>}

function Workshop(){return <><color attach="background" args={['#02070b']}/><ambientLight intensity={1.8}/><directionalLight position={[5,9,6]} intensity={4.5} castShadow/><pointLight position={[-5,4,2]} intensity={12}/><pointLight position={[5,4,-4]} intensity={10}/><Garage/><Bike scale={1.25}/><OrbitControls enableDamping enablePan={false} minDistance={3} maxDistance={12} target={[0,1,0]}/></>}

function Track(){return <group><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.05,0]} receiveShadow><planeGeometry args={[90,60]}/><meshStandardMaterial color="#161b1f" roughness={.95}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[0,.01,0]}><ringGeometry args={[14,28,96]}/><meshStandardMaterial color="#30363a" roughness={.9}/></mesh>{[-16,16].map(x=><mesh key={x} position={[x,.35,0]}><boxGeometry args={[.35,.7,60]}/><meshStandardMaterial color="#343b40"/></mesh>)}<mesh position={[0,.08,-14]}><boxGeometry args={[28,.12,.5]}/><meshStandardMaterial color="#eee"/></mesh><mesh position={[0,.09,-14.3]}><boxGeometry args={[3,.14,.08]}/><meshStandardMaterial color="#d22"/></mesh></group>}

function Ride(){const bike=useRef(),keys=useRef({}),speed=useRef(0),heading=useRef(0),{camera}=useThree(),[hud,setHud]=useState({speed:0,rpm:1200,gear:1});useEffect(()=>{const down=e=>{const k=e.key.toLowerCase();keys.current[k]=true;if(k==='r'){speed.current=0;heading.current=0;bike.current?.position.set(0,.02,18)}};const up=e=>{keys.current[e.key.toLowerCase()]=false};window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[]);useFrame((_,dt)=>{if(!bike.current)return;const k=keys.current,throttle=k.w||k.arrowup,brake=k.s||k.arrowdown||k[' '],steer=(k.a||k.arrowleft?-1:0)+(k.d||k.arrowright?1:0);speed.current=throttle?Math.min(28,speed.current+dt*12):Math.max(0,speed.current-dt*2.4);if(brake)speed.current=Math.max(0,speed.current-dt*18);heading.current+=steer*dt*.9*Math.min(1,speed.current/7);bike.current.position.x+=Math.sin(heading.current)*speed.current*dt;bike.current.position.z+=Math.cos(heading.current)*speed.current*dt;bike.current.rotation.y=heading.current+Math.PI;bike.current.rotation.z=-steer*.08;if(Math.abs(bike.current.position.x)>38||Math.abs(bike.current.position.z)>27){bike.current.position.set(0,.02,18);speed.current=0;heading.current=0}const p=bike.current.position;camera.position.lerp(new THREE.Vector3(p.x-Math.sin(heading.current)*7,3.4,p.z-Math.cos(heading.current)*7),1-Math.pow(.001,dt));camera.lookAt(p.x,1,p.z);setHud({speed:Math.round(speed.current*9.2),rpm:Math.round(1200+speed.current*330),gear:Math.max(1,Math.min(6,Math.floor(speed.current/4.5)+1))})});return <><color attach="background" args={['#06090b']}/><ambientLight intensity={1.7}/><directionalLight position={[10,16,6]} intensity={5} castShadow/><Track/><Bike refObj={bike} position={[0,.02,18]}/><Html fullscreen><div className="ride-hud"><div className="ride-top"><span>VEHICLELAB // RACE DEMO</span><span>TEST RIDE</span></div><div className="ride-speed"><b>{hud.speed}</b><span>KM/H</span></div><div className="ride-metrics"><span>RPM <b>{hud.rpm}</b></span><span>GEAR <b>{hud.gear}</b></span></div><div className="ride-controls"><b>W / ↑</b> THROTTLE <b>S / ↓</b> BRAKE <b>A / D</b> STEER <b>R</b> RESET</div></div></Html></>}

export default function VehicleLabAssets(){const[mode,setMode]=useState('workshop');return <div className="vehicle-lab"><div className="lab-topbar"><div><div className="brand">VEHICLE<span>LAB</span></div><div className="micro">REAL 3D VEHICLE WORKSHOP</div></div><div className="vehicle-name">KAWASAKI NINJA 650 <span>2021</span> // GLB</div><div className="top-actions"><button className={mode==='workshop'?'active':''} onClick={()=>setMode('workshop')}>WORKSHOP</button><button className={mode==='ride'?'active ride':''} onClick={()=>setMode('ride')}>TEST RIDE</button></div></div><Canvas shadows camera={{position:[6,3,7],fov:50}} dpr={[1,1.5]}><Suspense fallback={<Html center><div className="loading-text">LOADING 3D VEHICLE...</div></Html>}>{mode==='workshop'?<Workshop/>:<Ride/>}</Suspense></Canvas>{mode==='workshop'&&<><div className="glass parts-panel"><div className="panel-title">WORKSHOP</div><div className="part-list"><div className="part selected"><div><b>COMPLETE MOTORCYCLE</b><small>REAL SCANNED GLB</small></div><strong>3D</strong></div><div className="part"><div><b>ENGINE ASSEMBLY</b><small>DISASSEMBLY / REPAIR</small></div><strong>NEXT</strong></div><div className="part"><div><b>FRONT ASSEMBLY</b><small>BRAKE / WHEEL / FORK</small></div><strong>NEXT</strong></div><div className="part"><div><b>REAR ASSEMBLY</b><small>CHAIN / SPROCKET / WHEEL</small></div><strong>NEXT</strong></div></div></div><div className="glass stats-panel"><div className="panel-title">LIVE VEHICLE STATE</div><div className="stat">POWER <b>68 HP</b></div><div className="stat">WEIGHT <b>196 KG</b></div><div className="stat">GRIP <b>82%</b></div><div className="stat">BRAKING <b>80%</b></div><div className="divider"/><div className="selected-card"><b>RACE DEMO READY</b><span>STABLE LOCAL TRACK</span></div><button className="ride-launch" onClick={()=>setMode('ride')}>ENTER RACE TRACK</button></div></>}{mode==='workshop'&&<><div className="center-callout"><div className="reticle">◇</div>DRAG TO ORBIT · SCROLL TO ZOOM · ENTER RACE TRACK</div><div className="bottom-hud"><span><b>DRAG</b> ORBIT</span><span><b>SCROLL</b> ZOOM</span><span><b>TEST RIDE</b> RACE MODE</span></div></>}{mode==='ride'&&<div className="center-callout"><div className="reticle">◇</div>W / A / S / D TO RIDE · R TO RESET</div>}</div>}
